version: "3.8"

services:
  documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_junior
    command: serve --dev-addr=0.0.0.0:8011 --watch-theme
    restart: unless-stopped
    ports:
      - "8100:8011"
    volumes:
      - ./documentation:/docs:ro