services:
  documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_junior
    command: serve --dev-addr=0.0.0.0:8011 --watch-theme
    restart: unless-stopped
    ports:
      - "8100:8011"
    volumes:
      - ./documentation:/docs:ro
  local_database:
    image: postgres:16-alpine
    container_name: local_database
    hostname: local_database
    restart: always
    env_file:
      - .env
    ports:
      - "6655:${POSTGRES_PORT}"
    volumes:
      - postgres_datastorage:/var/lib/postgresgl/data
    networks:
      - main_network
  backend_api:
    build:
      dockerfile: Dockerfile
      context: ./backend_api
    container_name: backend_api
    hostname: backend_api
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend_api/app:/app
    ports:
      - "25000:25000"
    command: |
      sh -c "
      alembic upgrade head && \
      uvicorn main:app --port=25000 --host=0.0.0.0 --reload
      "
    networks:
      - main_network

  nginx_2:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - main_network


networks:
  main_network:
    driver: bridge
volumes:
  postgres_datastorage:
    external: false